# Generated by Django 3.2.5 on 2021-08-04 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('give_print', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='name',
            new_name='material',
        ),
    ]
