# Generated by Django 3.2.5 on 2021-07-25 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('give_print', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printer',
            old_name='prniting_technology',
            new_name='printing_technology',
        ),
    ]
