# Generated by Django 3.2.5 on 2021-08-04 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('give_print', '0002_rename_name_material_material'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printer',
            old_name='printing_process',
            new_name='process',
        ),
        migrations.RenameField(
            model_name='process',
            old_name='name',
            new_name='process',
        ),
        migrations.RemoveField(
            model_name='material',
            name='colours',
        ),
        migrations.RemoveField(
            model_name='process',
            name='materials',
        ),
    ]
