# Generated by Django 3.2.5 on 2021-07-15 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0002_newuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='desc',
        ),
    ]
