# Generated by Django 3.2.5 on 2021-07-25 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('give_print', '0001_initial'),
        ('get_print', '0002_alter_part_part'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infill', models.PositiveSmallIntegerField()),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='give_print.colour')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='give_print.material')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='give_print.process')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='get_print.customer')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='get_print.part')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='give_print.supplier')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project1.printspecification')),
            ],
        ),
    ]
