# Generated by Django 3.2.5 on 2021-08-09 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('give_print', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('get_print', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=500)),
                ('pin_code', models.PositiveSmallIntegerField()),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PrintSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_info', models.TextField(blank=True)),
                ('copies', models.PositiveIntegerField(default=1)),
                ('colours', smart_selects.db_fields.ChainedManyToManyField(chained_field='material', chained_model_field='materials', to='give_print.Colour')),
                ('material', smart_selects.db_fields.ChainedForeignKey(chained_field='process', chained_model_field='processes', on_delete=django.db.models.deletion.CASCADE, to='give_print.material')),
                ('process', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='give_print.process')),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project1.resolution')),
                ('units', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project1.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fulfilled', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='get_print.part')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='give_print.supplier')),
                ('shipping_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project1.shippinginfo')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project1.printspecification')),
            ],
        ),
    ]
