# Generated by Django 3.2.5 on 2021-08-04 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('get_print', '0001_initial'),
        ('project1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printspecification',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='get_print.part'),
        ),
    ]
