# Generated by Django 3.2.5 on 2021-08-04 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0002_alter_printspecification_part'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippinginfo',
            name='buyer',
        ),
    ]
