# Generated by Django 3.2.5 on 2021-08-04 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0003_remove_shippinginfo_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printspecification',
            name='buyer',
        ),
    ]
