# Generated by Django 3.2.5 on 2021-08-04 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0004_remove_printspecification_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printspecification',
            name='part',
        ),
    ]
